server:
  port: 8089
#  context-path: /SpringBootDemo
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/db_springboot?useUnicode = true&characterEncoding=UTF-8
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      useGlobalDataSourceStat: true
  redis:
    host: localhost
    port: 6379
    password: root
    pool:
      max-active: 500
      max-wait: 1500
      max-idle: 300
      min-idle: 1
    timeout: 3000
    database: 0

management:
  security:
    enabled: false

logging:
  level:
    root: INFO
    org:
      hibernate: INFO
      springframework:
        web: INFO
  config: classpath:log4j2.yml

content: "port: ${server.port },height: ${server.context-path}"