spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
      show_sql : true
    database-platform: org.hibernate.dialect.MySQL5Dialect
mybatis:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: com.ztc.entity
logging:
  level:
    root: debug
    org:
      hibernate: info
      springframework :
        web : info
  path: G://
  file: log.log
  config: classpath:log4j2.yml
