spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/db_springboot
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show_sql : true
    database-platform: org.hibernate.dialect.MySQL5Dialect