server:
  port: 8089
#  context-path: /SpringBootDemo
  session:
    timeout: 1800

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/db_springboot?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
    druid:
      initial-size: 8
      max-active: 64
      min-idle: 8
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 100
      max-open-prepared-statements: 32
      validation-query: SELECT 'x' FROM DUAL
      validation-query-timeout: 30000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 300000
      use-global-data-source-stat: true
      filters: stat
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000
    database: 0
    pool:
      max-active: 500
      max-wait: 1000
      max-idle: 100
      min-idle: 4
  session:
    store-type: redis
    redis:
      namespace: spring_session

management:
  security:
    enabled: true

logging:
  level:
    root: info
  config: classpath:log4j2.yml

content: "port: ${server.port },height: ${server.context-path}"