spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  http:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  session:
    store-type: redis
    redis:
      namespace: spring_session
  cache:
    type: redis
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/,classpath:/static/
    chain:
      enabled: true
      cache: true
      gzipped: true
      strategy:
        content:
          enabled: true
          paths: /**
    cache-period: 3600
mybatis:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: com.ztc.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    default-statement-timeout: 60000
    local-cache-scope: statement
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

pagehelper:
  reasonable: true
  supportMethodsArguments: true
  offset-as-page-num: true
  row-bounds-with-count: true
  page-size-zero: true

management:
  security:
    enabled: true

logging:
  level:
    root: info
  config: classpath:log4j2.yml
  file: logs/log.log