package com.ztc.entity.mybatis;

import org.joda.money.Money;

import java.io.Serializable;
import java.util.Date;

public class Coffee implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * t_coffee
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_coffee.id
     *
     * @mbg.generated
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_coffee.name
     *
     * @mbg.generated
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_coffee.price
     *
     * @mbg.generated
     */
    private Money price;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_coffee.create_time
     *
     * @mbg.generated
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_coffee.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_coffee.id
     *
     * @return the value of t_coffee.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_coffee.id
     *
     * @param id the value for t_coffee.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_coffee
     *
     * @mbg.generated
     */
    public Coffee withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_coffee.name
     *
     * @return the value of t_coffee.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_coffee.name
     *
     * @param name the value for t_coffee.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_coffee
     *
     * @mbg.generated
     */
    public Coffee withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_coffee.price
     *
     * @return the value of t_coffee.price
     * @mbg.generated
     */
    public Money getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_coffee.price
     *
     * @param price the value for t_coffee.price
     * @mbg.generated
     */
    public void setPrice(Money price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_coffee
     *
     * @mbg.generated
     */
    public Coffee withPrice(Money price) {
        this.setPrice(price);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_coffee.create_time
     *
     * @return the value of t_coffee.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_coffee.create_time
     *
     * @param createTime the value for t_coffee.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_coffee
     *
     * @mbg.generated
     */
    public Coffee withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_coffee.update_time
     *
     * @return the value of t_coffee.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_coffee.update_time
     *
     * @param updateTime the value for t_coffee.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_coffee
     *
     * @mbg.generated
     */
    public Coffee withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_coffee
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", price=").append(price);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}